'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Download, Copy, Check, Code, FileText } from 'lucide-react'
import type { RobloxElement, AnimationKeyframe, Project } from '../../types/roblox'

interface ExportDialogProps {
  elements: RobloxElement[]
  keyframes: AnimationKeyframe[]
  project: Project
  onClose: () => void
}

export default function ExportDialog({ elements, keyframes, project, onClose }: ExportDialogProps): JSX.Element {
  const [exportType, setExportType] = useState<'lua' | 'json'>('lua')
  const [exportSettings, setExportSettings] = useState({
    includeComments: true,
    minifyCode: false,
    sprSettings: {
      frequency: 120,
      damping: 0.8,
      speed: 1
    }
  })
  const [copied, setCopied] = useState<boolean>(false)

  const generateLuaCode = (): string => {
    const { includeComments, minifyCode, sprSettings } = exportSettings
    const indent = minifyCode ? '' : '    '
    const newline = minifyCode ? ' ' : '\n'
    
    let code = ''
    
    if (includeComments) {
      code += `-- Generated by Zomex•UIX${newline}`
      code += `-- Project: ${project.name}${newline}`
      code += `-- Elements: ${elements.length}, Keyframes: ${keyframes.length}${newline}${newline}`
    }
    
    // SPR Library setup
    code += `local SPR = require(script.SPR)${newline}${newline}`
    
    if (includeComments) {
      code += `-- SPR Configuration${newline}`
    }
    code += `local sprConfig = {${newline}`
    code += `${indent}frequency = ${sprSettings.frequency},${newline}`
    code += `${indent}damping = ${sprSettings.damping},${newline}`
    code += `${indent}speed = ${sprSettings.speed}${newline}`
    code += `}${newline}${newline}`
    
    // Create elements
    if (includeComments) {
      code += `-- Create UI Elements${newline}`
    }
    
    elements.forEach((element, index) => {
      const varName = element.name.replace(/[^a-zA-Z0-9]/g, '_')
      const props = element.properties
      
      code += `local ${varName} = Instance.new("${element.type}")${newline}`
      code += `${varName}.Name = "${element.name}"${newline}`
      
      // Set properties
      if (props.Position) {
        code += `${varName}.Position = UDim2.new(${props.Position.X.Scale}, ${props.Position.X.Offset}, ${props.Position.Y.Scale}, ${props.Position.Y.Offset})${newline}`
      }
      
      if (props.Size) {
        code += `${varName}.Size = UDim2.new(${props.Size.X.Scale}, ${props.Size.X.Offset}, ${props.Size.Y.Scale}, ${props.Size.Y.Offset})${newline}`
      }
      
      if (props.BackgroundColor3) {
        code += `${varName}.BackgroundColor3 = Color3.new(${props.BackgroundColor3.R}, ${props.BackgroundColor3.G}, ${props.BackgroundColor3.B})${newline}`
      }
      
      if (props.BackgroundTransparency !== undefined) {
        code += `${varName}.BackgroundTransparency = ${props.BackgroundTransparency}${newline}`
      }
      
      if (props.BorderSizePixel !== undefined) {
        code += `${varName}.BorderSizePixel = ${props.BorderSizePixel}${newline}`
      }
      
      if (props.BorderColor3) {
        code += `${varName}.BorderColor3 = Color3.new(${props.BorderColor3.R}, ${props.BorderColor3.G}, ${props.BorderColor3.B})${newline}`
      }
      
      if (props.Visible !== undefined) {
        code += `${varName}.Visible = ${props.Visible}${newline}`
      }
      
      if (props.ZIndex !== undefined) {
        code += `${varName}.ZIndex = ${props.ZIndex}${newline}`
      }
      
      if (props.ClipsDescendants !== undefined) {
        code += `${varName}.ClipsDescendants = ${props.ClipsDescendants}${newline}`
      }
      
      if (props.AnchorPoint) {
        code += `${varName}.AnchorPoint = Vector2.new(${props.AnchorPoint.X}, ${props.AnchorPoint.Y})${newline}`
      }
      
      // Text properties
      if (props.Text !== undefined) {
        code += `${varName}.Text = "${props.Text}"${newline}`
      }
      
      if (props.TextColor3) {
        code += `${varName}.TextColor3 = Color3.new(${props.TextColor3.R}, ${props.TextColor3.G}, ${props.TextColor3.B})${newline}`
      }
      
      if (props.TextSize !== undefined) {
        code += `${varName}.TextSize = ${props.TextSize}${newline}`
      }
      
      if (props.Font) {
        code += `${varName}.Font = Enum.Font.${props.Font}${newline}`
      }
      
      if (props.TextXAlignment) {
        code += `${varName}.TextXAlignment = Enum.TextXAlignment.${props.TextXAlignment}${newline}`
      }
      
      if (props.TextYAlignment) {
        code += `${varName}.TextYAlignment = Enum.TextYAlignment.${props.TextYAlignment}${newline}`
      }
      
      // Image properties
      if (props.Image) {
        code += `${varName}.Image = "${props.Image}"${newline}`
      }
      
      if (props.ImageColor3) {
        code += `${varName}.ImageColor3 = Color3.new(${props.ImageColor3.R}, ${props.ImageColor3.G}, ${props.ImageColor3.B})${newline}`
      }
      
      if (props.ImageTransparency !== undefined) {
        code += `${varName}.ImageTransparency = ${props.ImageTransparency}${newline}`
      }
      
      if (props.ScaleType) {
        code += `${varName}.ScaleType = Enum.ScaleType.${props.ScaleType}${newline}`
      }
      
      // UI Effects
      if (props.UICorner) {
        code += `local ${varName}_Corner = Instance.new("UICorner")${newline}`
        code += `${varName}_Corner.CornerRadius = UDim.new(0, ${props.UICorner.CornerRadius})${newline}`
        code += `${varName}_Corner.Parent = ${varName}${newline}`
      }
      
      if (props.UIStroke) {
        code += `local ${varName}_Stroke = Instance.new("UIStroke")${newline}`
        code += `${varName}_Stroke.Thickness = ${props.UIStroke.Thickness}${newline}`
        code += `${varName}_Stroke.Parent = ${varName}${newline}`
      }
      
      if (props.UIPadding) {
        code += `local ${varName}_Padding = Instance.new("UIPadding")${newline}`
        if (props.UIPadding.PaddingLeft !== undefined) {
          code += `${varName}_Padding.PaddingLeft = UDim.new(0, ${props.UIPadding.PaddingLeft})${newline}`
        }
        if (props.UIPadding.PaddingRight !== undefined) {
          code += `${varName}_Padding.PaddingRight = UDim.new(0, ${props.UIPadding.PaddingRight})${newline}`
        }
        if (props.UIPadding.PaddingTop !== undefined) {
          code += `${varName}_Padding.PaddingTop = UDim.new(0, ${props.UIPadding.PaddingTop})${newline}`
        }
        if (props.UIPadding.PaddingBottom !== undefined) {
          code += `${varName}_Padding.PaddingBottom = UDim.new(0, ${props.UIPadding.PaddingBottom})${newline}`
        }
        code += `${varName}_Padding.Parent = ${varName}${newline}`
      }
      
      code += newline
    })
    
    // Animation functions
    if (keyframes.length > 0) {
      if (includeComments) {
        code += `-- Animation Functions${newline}`
      }
      
      // Group keyframes by element
      const elementAnimations = new Map<string, AnimationKeyframe[]>()
      keyframes.forEach(kf => {
        if (!elementAnimations.has(kf.elementId)) {
          elementAnimations.set(kf.elementId, [])
        }
        elementAnimations.get(kf.elementId)!.push(kf)
      })
      
      code += `local function playAnimation()${newline}`
      
      elementAnimations.forEach((elementKeyframes, elementId) => {
        const element = elements.find(el => el.id === elementId)
        if (!element) return
        
        const varName = element.name.replace(/[^a-zA-Z0-9]/g, '_')
        const sortedKeyframes = elementKeyframes.sort((a, b) => a.time - b.time)
        
        sortedKeyframes.forEach((keyframe, index) => {
          if (index === 0) {
            code += `${indent}-- Animate ${element.name}${newline}`
          }
          
          code += `${indent}task.wait(${keyframe.time})${newline}`
          
          // Generate SPR animation for each property
          Object.entries(keyframe.properties).forEach(([propName, propValue]) => {
            if (propName === 'Position' && typeof propValue === 'object' && 'X' in propValue) {
              code += `${indent}SPR.target(${varName}, sprConfig, {${newline}`
              code += `${indent}${indent}Position = UDim2.new(${propValue.X.Scale}, ${propValue.X.Offset}, ${propValue.Y.Scale}, ${propValue.Y.Offset})${newline}`
              code += `${indent}})${newline}`
            } else if (propName === 'Size' && typeof propValue === 'object' && 'X' in propValue) {
              code += `${indent}SPR.target(${varName}, sprConfig, {${newline}`
              code += `${indent}${indent}Size = UDim2.new(${propValue.X.Scale}, ${propValue.X.Offset}, ${propValue.Y.Scale}, ${propValue.Y.Offset})${newline}`
              code += `${indent}})${newline}`
            } else if (propName === 'BackgroundColor3' && typeof propValue === 'object' && 'R' in propValue) {
              code += `${indent}SPR.target(${varName}, sprConfig, {${newline}`
              code += `${indent}${indent}BackgroundColor3 = Color3.new(${propValue.R}, ${propValue.G}, ${propValue.B})${newline}`
              code += `${indent}})${newline}`
            } else if (typeof propValue === 'number') {
              code += `${indent}SPR.target(${varName}, sprConfig, {${newline}`
              code += `${indent}${indent}${propName} = ${propValue}${newline}`
              code += `${indent}})${newline}`
            }
          })
        })
      })
      
      code += `end${newline}${newline}`
      
      if (includeComments) {
        code += `-- Start animation${newline}`
      }
      code += `playAnimation()${newline}`
    }
    
    return code
  }
  
  const generateJsonCode = (): string => {
    const exportData = {
      project: {
        name: project.name,
        version: "1.0.0",
        created: new Date().toISOString()
      },
      elements,
      keyframes,
      settings: project.settings
    }
    
    return JSON.stringify(exportData, null, 2)
  }
  
  const getExportCode = (): string => {
    return exportType === 'lua' ? generateLuaCode() : generateJsonCode()
  }
  
  const handleCopy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(getExportCode())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }
  
  const handleDownload = (): void => {
    const code = getExportCode()
    const filename = `${project.name.replace(/[^a-zA-Z0-9]/g, '_')}.${exportType === 'lua' ? 'lua' : 'zuix.json'}`
    
    const blob = new Blob([code], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    
    URL.revokeObjectURL(url)
  }

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
      >
        <motion.div
          className="bg-gray-900 rounded-lg border border-gray-800 w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col"
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="p-4 sm:p-6 border-b border-gray-800 flex items-center justify-between flex-shrink-0">
            <div className="flex items-center gap-3">
              <Download className="w-5 h-5 text-purple-400" />
              <h2 className="text-lg sm:text-xl font-semibold text-white">Export Project</h2>
            </div>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-gray-800 transition-colors"
            >
              <X className="w-5 h-5 text-gray-400" />
            </button>
          </div>

          {/* Content */}
          <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
            {/* Settings Panel */}
            <div className="w-full lg:w-80 p-4 sm:p-6 border-b lg:border-b-0 lg:border-r border-gray-800 space-y-4 sm:space-y-6 overflow-y-auto">
              {/* Export Type */}
              <div className="space-y-3">
                <label className="block text-sm font-medium text-white">Export Format</label>
                <div className="space-y-2">
                  <button
                    onClick={() => setExportType('lua')}
                    className={`w-full p-3 rounded-lg border transition-colors text-left ${
                      exportType === 'lua'
                        ? 'border-purple-400 bg-purple-900/20 text-white'
                        : 'border-gray-700 bg-gray-800 text-gray-300 hover:bg-gray-700'
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <Code className="w-4 h-4" />
                      <div>
                        <div className="text-sm font-medium">Lua/Luau</div>
                        <div className="text-xs text-gray-400">Ready-to-use Roblox code</div>
                      </div>
                    </div>
                  </button>
                  <button
                    onClick={() => setExportType('json')}
                    className={`w-full p-3 rounded-lg border transition-colors text-left ${
                      exportType === 'json'
                        ? 'border-purple-400 bg-purple-900/20 text-white'
                        : 'border-gray-700 bg-gray-800 text-gray-300 hover:bg-gray-700'
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <FileText className="w-4 h-4" />
                      <div>
                        <div className="text-sm font-medium">.zuix.json</div>
                        <div className="text-xs text-gray-400">Project backup format</div>
                      </div>
                    </div>
                  </button>
                </div>
              </div>

              {/* Lua Settings */}
              {exportType === 'lua' && (
                <>
                  <div className="space-y-3">
                    <label className="block text-sm font-medium text-white">Code Options</label>
                    <div className="space-y-2">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={exportSettings.includeComments}
                          onChange={(e) => setExportSettings(prev => ({ ...prev, includeComments: e.target.checked }))}
                          className="w-4 h-4 text-purple-600 bg-gray-800 border-gray-700 rounded focus:ring-purple-500"
                        />
                        <span className="text-sm text-gray-300">Include comments</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={exportSettings.minifyCode}
                          onChange={(e) => setExportSettings(prev => ({ ...prev, minifyCode: e.target.checked }))}
                          className="w-4 h-4 text-purple-600 bg-gray-800 border-gray-700 rounded focus:ring-purple-500"
                        />
                        <span className="text-sm text-gray-300">Minify code</span>
                      </label>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <label className="block text-sm font-medium text-white">SPR Animation Settings</label>
                    <div className="space-y-3">
                      <div>
                        <label className="block text-xs text-gray-400 mb-1">Frequency</label>
                        <input
                          type="number"
                          min="1"
                          max="300"
                          value={exportSettings.sprSettings.frequency}
                          onChange={(e) => setExportSettings(prev => ({
                            ...prev,
                            sprSettings: { ...prev.sprSettings, frequency: parseInt(e.target.value) || 120 }
                          }))}
                          className="w-full px-2 py-1 bg-gray-800 border border-gray-700 rounded text-xs text-white focus:outline-none focus:border-purple-400"
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-gray-400 mb-1">Damping</label>
                        <input
                          type="number"
                          min="0"
                          max="2"
                          step="0.1"
                          value={exportSettings.sprSettings.damping}
                          onChange={(e) => setExportSettings(prev => ({
                            ...prev,
                            sprSettings: { ...prev.sprSettings, damping: parseFloat(e.target.value) || 0.8 }
                          }))}
                          className="w-full px-2 py-1 bg-gray-800 border border-gray-700 rounded text-xs text-white focus:outline-none focus:border-purple-400"
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-gray-400 mb-1">Speed</label>
                        <input
                          type="number"
                          min="0.1"
                          max="5"
                          step="0.1"
                          value={exportSettings.sprSettings.speed}
                          onChange={(e) => setExportSettings(prev => ({
                            ...prev,
                            sprSettings: { ...prev.sprSettings, speed: parseFloat(e.target.value) || 1 }
                          }))}
                          className="w-full px-2 py-1 bg-gray-800 border border-gray-700 rounded text-xs text-white focus:outline-none focus:border-purple-400"
                        />
                      </div>
                    </div>
                  </div>
                </>
              )}
            </div>

            {/* Code Preview */}
            <div className="flex-1 flex flex-col overflow-hidden">
              <div className="p-4 sm:p-6 border-b border-gray-800 flex items-center justify-between flex-shrink-0">
                <h3 className="text-sm font-medium text-white">
                  {exportType === 'lua' ? 'Generated Lua Code' : 'Project JSON'}
                </h3>
                <div className="flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-2 px-3 py-1.5 text-xs bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors"
                  >
                    {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                </div>
              </div>
              
              <div className="flex-1 overflow-auto">
                <pre className="p-4 sm:p-6 text-xs sm:text-sm font-mono text-gray-300 whitespace-pre-wrap break-words">
                  {getExportCode()}
                </pre>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="p-4 sm:p-6 border-t border-gray-800 flex justify-end gap-3 flex-shrink-0">
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm text-gray-400 hover:text-white transition-colors"
            >
              Close
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-2 text-sm bg-gradient-to-r from-[#fff0f5] to-[#ffd1db] text-black rounded-lg hover:opacity-80 transition-opacity"
            >
              Download {exportType === 'lua' ? '.lua' : '.zuix.json'}
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}