'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { useState, useMemo, useEffect } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Slider } from '@/components/ui/slider'
import { Textarea } from '@/components/ui/textarea'
import { 
  Download, 
  Copy, 
  Code, 
  Settings, 
  CheckCircle,
  FileText,
  Zap
} from 'lucide-react'
import { saveAs } from 'file-saver'
import type { Project, ExportConfig, SPRConfig, FunctionAnimation, ROBLOX_EVENTS, ZuixFile } from '@/types/roblox'
import { ROBLOX_EVENTS } from '@/types/roblox'

interface ExportDialogProps {
  open: boolean
  onClose: () => void
  project: Project
  exportConfig?: ExportConfig
  onExportConfigChange?: (config: ExportConfig) => void
}

export function ExportDialog({ open, onClose, project, exportConfig: propExportConfig, onExportConfigChange }: ExportDialogProps): JSX.Element {
  // Use prop exportConfig or load from localStorage
  const [exportConfig, setExportConfig] = useState<ExportConfig>(() => {
    if (propExportConfig) {
      return propExportConfig
    }
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('zomex-export-config')
      if (saved) {
        try {
          return JSON.parse(saved)
        } catch (error) {
          console.error('Failed to load export config:', error)
        }
      }
    }
    return {
      includeComments: true,
      minify: false,
      sprSettings: {
        dampingRatio: 0.7,
        undampedFrequency: 4
      },
      targetVersion: 'Luau',
      animationType: 'loop',
      screenGuiSettings: {
        name: 'ScreenGui',
        ignoreGuiInset: false,
        resetOnSpawn: false,
        displayOrder: 0,
        zIndexBehavior: 'Sibling',
        autoLocalize: false,
        enabled: true
      }
    }
  })
  const [showExportDropdown, setShowExportDropdown] = useState<boolean>(false)
  const [copied, setCopied] = useState<boolean>(false)

  // Save export config to localStorage and notify parent whenever it changes
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('zomex-export-config', JSON.stringify(exportConfig))
    }
    if (onExportConfigChange) {
      onExportConfigChange(exportConfig)
    }
  }, [exportConfig, onExportConfigChange])

  // Generate Lua code
  const generatedCode = useMemo(() => {
    return generateLuaCode(project, exportConfig)
  }, [project, exportConfig])

  // Generate the complete Lua/Luau code with SPR animations
  function generateLuaCode(project: Project, config: ExportConfig): string {
    const { includeComments, minify, sprSettings, targetVersion } = config
    const indent = minify ? '' : '    '
    const newline = minify ? ' ' : '\n'
    const comment = (text: string) => includeComments ? `-- ${text}${newline}` : ''

    let code = ''

    // Header
    code += comment('Generated by dalley. - Roblox UI Animation Tool')
    code += comment(`Project: ${project.name}`)
    code += comment(`Elements: ${project.elements.length}`)
    code += comment(`Animations: ${project.animations.length}`)
    code += comment(`Target: ${targetVersion}`)
    code += newline

    // Check if we have any animations at all
    const hasAnimations = project.animations.length > 0 || 
      (project.functionAnimations && project.functionAnimations.some(fa => fa.keyframes && fa.keyframes.length > 0))

    // SPR Library import - ONLY if animations exist
    if (hasAnimations) {
      code += comment('SPR Animation Library - Load via HttpGet')
      code += `local SPR = loadstring(game:HttpGet("https://raw.githubusercontent.com/Fraktality/spr/refs/heads/master/spr.lua"))()${newline}`
      code += newline
    }

    // Services - ONLY include what we actually need
    code += comment('Services')
    code += `local Players = game:GetService("Players")${newline}`
    // Only include RunService if we have animations
    if (hasAnimations) {
      code += `local RunService = game:GetService("RunService")${newline}`
    }
    code += newline

    // Variables
    code += comment('Variables')
    code += `local player = Players.LocalPlayer${newline}`
    code += `local playerGui = player:WaitForChild("PlayerGui")${newline}`
    code += newline

    // Create ScreenGui - Always parent to PlayerGui for exploit compatibility
    code += comment('Create main ScreenGui')
    code += `local screenGui = Instance.new("ScreenGui")${newline}`
    
    // Apply ScreenGui settings
    const guiSettings = config.screenGuiSettings || {
      name: 'ScreenGui',
      ignoreGuiInset: false,
      resetOnSpawn: false,
      displayOrder: 0,
      zIndexBehavior: 'Sibling',
      autoLocalize: false,
      enabled: true
    }
    
    code += `screenGui.Name = "${guiSettings.name || project.name.replace(/[^a-zA-Z0-9]/g, '')}"${newline}`
    code += `screenGui.IgnoreGuiInset = ${guiSettings.ignoreGuiInset}${newline}`
    code += `screenGui.ResetOnSpawn = ${guiSettings.resetOnSpawn}${newline}`
    code += `screenGui.DisplayOrder = ${guiSettings.displayOrder}${newline}`
    code += `screenGui.ZIndexBehavior = Enum.ZIndexBehavior.${guiSettings.zIndexBehavior}${newline}`
    code += `screenGui.AutoLocalize = ${guiSettings.autoLocalize}${newline}`
    code += `screenGui.Enabled = ${guiSettings.enabled}${newline}`
    code += `screenGui.Parent = playerGui${newline}`
    code += newline

    // Create UI elements
    code += comment('Create UI Elements')
    const elementVariables: Record<string, string> = {}

    project.elements.forEach((element, index) => {
      const varName = element.name.replace(/\s+/g, '') // Use actual element name without spaces
      elementVariables[element.id] = varName

      code += comment(`Create ${element.name} (${element.type})`)
      code += `local ${varName} = Instance.new("${element.type}")${newline}`
      code += `${varName}.Name = "${element.name}"${newline}`

      // Set properties (exclude parent and UI effects as they're handled separately)
      Object.entries(element.properties).forEach(([key, value]) => {
        if (key === 'parent') return // Skip parent property - handled in parent relationships section
        if (key === 'UICorner' || key === 'UIStroke' || key === 'UIGradient' || key === 'UIListLayout' || key === 'UIGridLayout') return // Skip UI effects - handled separately
        const luaValue = convertToLuaValue(value, key)
        if (luaValue) {
          code += `${varName}.${key} = ${luaValue}${newline}`
        }
      })

      // Create UI effects for this element
      const effects = []
      
      // UICorner
      if (element.properties.UICorner && element.properties.UICorner.CornerRadius && element.properties.UICorner.CornerRadius.Offset > 0) {
        effects.push('UICorner')
        code += comment(`Create UICorner for ${element.name}`)
        code += `local ${varName}_UICorner = Instance.new("UICorner")${newline}`
        code += `${varName}_UICorner.CornerRadius = UDim.new(${element.properties.UICorner.CornerRadius.Scale || 0}, ${element.properties.UICorner.CornerRadius.Offset})${newline}`
        code += `${varName}_UICorner.Parent = ${varName}${newline}`
        code += newline
      }
      
      // UIStroke (allow Thickness = 0 when using ScaledSize)
      if (element.properties.UIStroke && (element.properties.UIStroke.Thickness > 0 || element.properties.UIStroke.Thickness === 0)) {
        effects.push('UIStroke')
        code += comment(`Create UIStroke for ${element.name}`)
        code += `local ${varName}_UIStroke = Instance.new("UIStroke")${newline}`
        code += `${varName}_UIStroke.Thickness = ${element.properties.UIStroke.Thickness}${newline}`
        
        // If UIGradient is applied to UIStroke, force white color (gradients are multiplicative)
        if (element.properties.UIStroke.UIGradient) {
          code += `${varName}_UIStroke.Color = Color3.new(1, 1, 1)${newline}`
        } else if (element.properties.UIStroke.Color) {
          const strokeColor = convertToLuaValue(element.properties.UIStroke.Color)
          if (strokeColor) {
            code += `${varName}_UIStroke.Color = ${strokeColor}${newline}`
          }
        }
        
        if (element.properties.UIStroke.Transparency !== undefined) {
          code += `${varName}_UIStroke.Transparency = ${element.properties.UIStroke.Transparency}${newline}`
        }
        
        // New UIStroke properties
        if (element.properties.UIStroke.StrokeSizingMode && element.properties.UIStroke.StrokeSizingMode !== 'FixedSize') {
          code += `${varName}_UIStroke.StrokeSizingMode = Enum.StrokeSizingMode.${element.properties.UIStroke.StrokeSizingMode}${newline}`
        }
        
        if (element.properties.UIStroke.BorderOffset && (element.properties.UIStroke.BorderOffset.Scale !== 0 || element.properties.UIStroke.BorderOffset.Offset !== 0)) {
          code += `${varName}_UIStroke.BorderOffset = UDim.new(${element.properties.UIStroke.BorderOffset.Scale}, ${element.properties.UIStroke.BorderOffset.Offset})${newline}`
        }
        
        // UIStroke UIGradient
        if (element.properties.UIStroke.UIGradient) {
          code += comment(`Create UIGradient for ${element.name} stroke`)
          code += `local ${varName}_UIStroke_UIGradient = Instance.new(\"UIGradient\")${newline}`
          
          // Set rotation
          if (element.properties.UIStroke.UIGradient.Rotation !== undefined) {
            code += `${varName}_UIStroke_UIGradient.Rotation = ${element.properties.UIStroke.UIGradient.Rotation}${newline}`
          }
          
          // Set color keypoints
          if (element.properties.UIStroke.UIGradient.Color && element.properties.UIStroke.UIGradient.Color.Keypoints) {
            const colorKeypoints = element.properties.UIStroke.UIGradient.Color.Keypoints
              .map(kp => `ColorSequenceKeypoint.new(${kp.Time}, Color3.new(${kp.Value.R}, ${kp.Value.G}, ${kp.Value.B}))`)
              .join(', ')
            code += `${varName}_UIStroke_UIGradient.Color = ColorSequence.new({${colorKeypoints}})${newline}`
          }
          
          // Set transparency keypoints
          if (element.properties.UIStroke.UIGradient.Transparency && element.properties.UIStroke.UIGradient.Transparency.Keypoints) {
            const transparencyKeypoints = element.properties.UIStroke.UIGradient.Transparency.Keypoints
              .map(kp => `NumberSequenceKeypoint.new(${kp.Time}, ${kp.Value})`)
              .join(', ')
            code += `${varName}_UIStroke_UIGradient.Transparency = NumberSequence.new({${transparencyKeypoints}})${newline}`
          }
          
          code += `${varName}_UIStroke_UIGradient.Parent = ${varName}_UIStroke${newline}`
          code += newline
        }
        
        code += `${varName}_UIStroke.Parent = ${varName}${newline}`
        code += newline
      }
      
      // UIGradient
      if (element.properties.UIGradient) {
        effects.push('UIGradient')
        code += comment(`Create UIGradient for ${element.name}`)
        code += `local ${varName}_UIGradient = Instance.new("UIGradient")${newline}`
        
        // Set rotation
        if (element.properties.UIGradient.Rotation !== undefined) {
          code += `${varName}_UIGradient.Rotation = ${element.properties.UIGradient.Rotation}${newline}`
        }
        
        // Set color keypoints
        if (element.properties.UIGradient.Color && element.properties.UIGradient.Color.Keypoints) {
          const colorKeypoints = element.properties.UIGradient.Color.Keypoints
            .map(kp => `ColorSequenceKeypoint.new(${kp.Time}, Color3.new(${kp.Value.R}, ${kp.Value.G}, ${kp.Value.B}))`)
            .join(', ')
          code += `${varName}_UIGradient.Color = ColorSequence.new({${colorKeypoints}})${newline}`
        }
        
        // Set transparency keypoints
        if (element.properties.UIGradient.Transparency && element.properties.UIGradient.Transparency.Keypoints) {
          const transparencyKeypoints = element.properties.UIGradient.Transparency.Keypoints
            .map(kp => `NumberSequenceKeypoint.new(${kp.Time}, ${kp.Value})`)
            .join(', ')
          code += `${varName}_UIGradient.Transparency = NumberSequence.new({${transparencyKeypoints}})${newline}`
        }
        
        code += `${varName}_UIGradient.Parent = ${varName}${newline}`
        code += newline
      }
      
      // UIListLayout
      if (element.properties.UIListLayout) {
        effects.push('UIListLayout')
        code += comment(`Create UIListLayout for ${element.name}`)
        code += `local ${varName}_UIListLayout = Instance.new("UIListLayout")${newline}`
        
        // Set properties
        code += `${varName}_UIListLayout.FillDirection = Enum.FillDirection.${element.properties.UIListLayout.FillDirection}${newline}`
        code += `${varName}_UIListLayout.SortOrder = Enum.SortOrder.${element.properties.UIListLayout.SortOrder}${newline}`
        code += `${varName}_UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.${element.properties.UIListLayout.HorizontalAlignment}${newline}`
        code += `${varName}_UIListLayout.VerticalAlignment = Enum.VerticalAlignment.${element.properties.UIListLayout.VerticalAlignment}${newline}`
        
        // Set Padding (UDim)
        if (element.properties.UIListLayout.Padding) {
          code += `${varName}_UIListLayout.Padding = UDim.new(${element.properties.UIListLayout.Padding.Scale}, ${element.properties.UIListLayout.Padding.Offset})${newline}`
        }
        
        // Set Wraps
        if (element.properties.UIListLayout.Wraps !== undefined) {
          code += `${varName}_UIListLayout.Wraps = ${element.properties.UIListLayout.Wraps}${newline}`
        }
        
        code += `${varName}_UIListLayout.Parent = ${varName}${newline}`
        code += newline
      }
      
      // UIGridLayout  
      if (element.properties.UIGridLayout) {
        effects.push('UIGridLayout')
        code += comment(`Create UIGridLayout for ${element.name}`)
        code += `local ${varName}_UIGridLayout = Instance.new("UIGridLayout")${newline}`
        
        // Set properties
        code += `${varName}_UIGridLayout.FillDirection = Enum.FillDirection.${element.properties.UIGridLayout.FillDirection}${newline}`
        code += `${varName}_UIGridLayout.SortOrder = Enum.SortOrder.${element.properties.UIGridLayout.SortOrder}${newline}`
        code += `${varName}_UIGridLayout.HorizontalAlignment = Enum.HorizontalAlignment.${element.properties.UIGridLayout.HorizontalAlignment}${newline}`
        code += `${varName}_UIGridLayout.VerticalAlignment = Enum.VerticalAlignment.${element.properties.UIGridLayout.VerticalAlignment}${newline}`
        code += `${varName}_UIGridLayout.StartCorner = Enum.StartCorner.${element.properties.UIGridLayout.StartCorner}${newline}`
        
        // Set CellPadding (UDim2)
        if (element.properties.UIGridLayout.CellPadding) {
          code += `${varName}_UIGridLayout.CellPadding = UDim2.new(${element.properties.UIGridLayout.CellPadding.X.Scale}, ${element.properties.UIGridLayout.CellPadding.X.Offset}, ${element.properties.UIGridLayout.CellPadding.Y.Scale}, ${element.properties.UIGridLayout.CellPadding.Y.Offset})${newline}`
        }
        
        // Set CellSize (UDim2)
        if (element.properties.UIGridLayout.CellSize) {
          code += `${varName}_UIGridLayout.CellSize = UDim2.new(${element.properties.UIGridLayout.CellSize.X.Scale}, ${element.properties.UIGridLayout.CellSize.X.Offset}, ${element.properties.UIGridLayout.CellSize.Y.Scale}, ${element.properties.UIGridLayout.CellSize.Y.Offset})${newline}`
        }
        
        code += `${varName}_UIGridLayout.Parent = ${varName}${newline}`
        code += newline
      }

      code += newline
    })

    // Set parent relationships after all elements are created
    code += comment('Set Parent Relationships - Parent to PlayerGui')
    project.elements.forEach((element, index) => {
      const varName = element.name.replace(/\s+/g, '') // Use actual element name without spaces
      
      // Determine parent
      let parentReference = 'screenGui'
      if (element.parent && element.parent !== 'script.Parent') {
        // Find the parent element and get its variable name
        const parentElement = project.elements.find(el => el.id === element.parent)
        if (parentElement) {
          parentReference = parentElement.name.replace(/\s+/g, '') // Use parent's actual name
        }
      }
      
      code += `${varName}.Parent = ${parentReference}${newline}`
    })
    code += newline

    // Animation functions - ONLY if animations exist
    if (hasAnimations && project.animations.length > 0) {
      code += comment('Animation Functions')
      
      // SPR Configuration
      code += comment('SPR Animation Configuration')
      code += `local sprConfig = {${newline}`
      code += `${indent}dampingRatio = ${sprSettings.dampingRatio},${newline}`
      code += `${indent}undampedFrequency = ${sprSettings.undampedFrequency}${newline}`
      code += `}${newline}`
      code += newline
      
      // Animation state
      code += comment('Animation State')
      code += `local animationTime = 0${newline}`
      code += `local isPlaying = false${newline}`
      code += `local lastKeyframes = {}${newline}`
      code += `local isLoop = ${config.animationType === 'loop' ? 'true' : 'false'}${newline}`
      code += newline
      
      // Create animation data structure
      code += `local animations = {${newline}`
      
      const animationsByElement = project.animations.reduce((acc, anim) => {
        if (!acc[anim.elementId]) acc[anim.elementId] = []
        acc[anim.elementId].push(anim)
        return acc
      }, {} as Record<string, typeof project.animations>)

      Object.entries(animationsByElement).forEach(([elementId, anims]) => {
        const varName = elementVariables[elementId]
        if (!varName) return

        code += `${indent}["${elementId}"] = {${newline}`
        code += `${indent}${indent}element = ${varName},${newline}`
        code += `${indent}${indent}keyframes = {${newline}`

        anims.sort((a, b) => a.time - b.time).forEach(anim => {
          code += `${indent}${indent}${indent}{${newline}`
          code += `${indent}${indent}${indent}${indent}time = ${anim.time},${newline}`
          code += `${indent}${indent}${indent}${indent}properties = {${newline}`
          
          Object.entries(anim.properties).forEach(([key, value]) => {
            const luaValue = convertToLuaValue(value, key)
            if (luaValue) {
              code += `${indent}${indent}${indent}${indent}${indent}${key} = ${luaValue},${newline}`
            }
          })
          
          code += `${indent}${indent}${indent}${indent}},${newline}`
          
          // Add per-keyframe spring settings
          const keyframeSprSettings = anim.sprSettings || sprSettings
          code += `${indent}${indent}${indent}${indent}sprSettings = {${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}dampingRatio = ${keyframeSprSettings.dampingRatio},${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}undampedFrequency = ${keyframeSprSettings.undampedFrequency}${newline}`
          code += `${indent}${indent}${indent}${indent}}${newline}`
          code += `${indent}${indent}${indent}},${newline}`
        })

        code += `${indent}${indent}}${newline}`
        code += `${indent}},${newline}`
      })

      code += `}${newline}`
      code += newline

      // Animation update function
      code += comment('Animation Update Function')
      code += `local function updateAnimation(deltaTime)${newline}`
      code += `${indent}if not isPlaying then return end${newline}`
      code += newline
      code += `${indent}animationTime = animationTime + deltaTime${newline}`
      code += `${indent}local totalDuration = ${project.duration}${newline}`
      code += newline
      code += `${indent}-- Handle animation end${newline}`
      code += `${indent}if animationTime > totalDuration then${newline}`
      code += `${indent}${indent}if isLoop then${newline}`
      code += `${indent}${indent}${indent}animationTime = 0${newline}`
      code += `${indent}${indent}${indent}lastKeyframes = {} -- Reset SPR state${newline}`
      code += `${indent}${indent}else${newline}`
      code += `${indent}${indent}${indent}animationTime = totalDuration${newline}`
      code += `${indent}${indent}${indent}isPlaying = false${newline}`
      code += `${indent}${indent}end${newline}`
      code += `${indent}end${newline}`
      code += newline
      code += `${indent}for elementId, animData in pairs(animations) do${newline}`
      code += `${indent}${indent}local element = animData.element${newline}`
      code += `${indent}${indent}local keyframes = animData.keyframes${newline}`
      code += newline
      code += `${indent}${indent}-- Find the next keyframe to animate to${newline}`
      code += `${indent}${indent}local nextKeyframe = nil${newline}`
      code += newline
      code += `${indent}${indent}-- Find the first keyframe that should be active at current time${newline}`
      code += `${indent}${indent}for i, keyframe in ipairs(keyframes) do${newline}`
      code += `${indent}${indent}${indent}if animationTime >= keyframe.time then${newline}`
      code += `${indent}${indent}${indent}${indent}nextKeyframe = keyframe${newline}`
      code += `${indent}${indent}${indent}end${newline}`
      code += `${indent}${indent}end${newline}`
      code += newline
      code += `${indent}${indent}if nextKeyframe then${newline}`
      code += `${indent}${indent}${indent}-- Only call SPR.target when entering a new keyframe for smooth spring animation${newline}`
      code += `${indent}${indent}${indent}local lastTime = lastKeyframes[elementId]${newline}`
      code += `${indent}${indent}${indent}if not lastTime or lastTime ~= nextKeyframe.time then${newline}`
      code += `${indent}${indent}${indent}${indent}-- Get keyframe-specific spring settings${newline}`
      code += `${indent}${indent}${indent}${indent}local keyframeSprSettings = nextKeyframe.sprSettings or sprConfig${newline}`
      code += `${indent}${indent}${indent}${indent}-- Animate element smoothly to keyframe target using SPR${newline}`
      code += `${indent}${indent}${indent}${indent}SPR.target(element, keyframeSprSettings.dampingRatio, keyframeSprSettings.undampedFrequency, nextKeyframe.properties)${newline}`
      code += `${indent}${indent}${indent}${indent}lastKeyframes[elementId] = nextKeyframe.time${newline}`
      code += `${indent}${indent}${indent}end${newline}`
      code += `${indent}${indent}end${newline}`
      code += `${indent}end${newline}`
      code += `end${newline}`
      code += newline

      // Animation controls
      code += comment('Animation Controls')
      code += `local function playAnimation()${newline}`
      code += `${indent}isPlaying = true${newline}`
      code += `end${newline}`
      code += newline
      code += `local function pauseAnimation()${newline}`
      code += `${indent}isPlaying = false${newline}`
      code += `end${newline}`
      code += newline
      code += `local function resetAnimation()${newline}`
      code += `${indent}animationTime = 0${newline}`
      code += `${indent}isPlaying = false${newline}`
      code += `${indent}lastKeyframes = {}${newline}`
      code += `end${newline}`
      code += newline

      // Connect to RunService
      code += comment('Connect animation to RunService')
      code += `RunService.Heartbeat:Connect(updateAnimation)${newline}`
      code += newline

      // Auto-start animation
      code += comment('Start animation automatically')
      code += `playAnimation()${newline}`
    }

    // Generate function animations
    const elementsWithFunctions = project.elements.filter(element => element.functions && element.functions.length > 0)
    if (elementsWithFunctions.length > 0) {
      code += comment('Function Animations')
      
      elementsWithFunctions.forEach(element => {
        const varName = elementVariables[element.id]
        if (!varName) return

        element.functions?.forEach(func => {
          if (!func.enabled) return // Skip disabled functions
          
          const functionAnimation = project.functionAnimations?.find(anim => anim.id === func.animationId)
          if (!functionAnimation || !functionAnimation.keyframes || functionAnimation.keyframes.length === 0) return
          
          code += comment(`${func.eventName} animation for ${element.name}`)
          code += comment(`Function: ${func.eventName} for ${element.name}`)
          code += `local function ${varName}_${func.eventName}()${newline}`
          
          // Function animation data structure
          code += `${indent}local functionAnimations = {${newline}`
          
          // Group keyframes by element for this function
          const keyframesByElement = functionAnimation.keyframes.reduce((acc, keyframe) => {
            if (!acc[keyframe.elementId]) acc[keyframe.elementId] = []
            acc[keyframe.elementId].push(keyframe)
            return acc
          }, {} as Record<string, typeof functionAnimation.keyframes>)
          
          // Generate animation data for each element that has keyframes in this function
          Object.entries(keyframesByElement).forEach(([elementId, keyframes]) => {
            const targetVarName = elementVariables[elementId]
            if (!targetVarName) return
            
            code += `${indent}${indent}["${elementId}"] = {${newline}`
            code += `${indent}${indent}${indent}element = ${targetVarName},${newline}`
            code += `${indent}${indent}${indent}keyframes = {${newline}`
            
            // Sort keyframes by time and generate each keyframe
            keyframes.sort((a, b) => a.time - b.time).forEach(keyframe => {
              code += `${indent}${indent}${indent}${indent}{${newline}`
              code += `${indent}${indent}${indent}${indent}${indent}time = ${keyframe.time},${newline}`
              code += `${indent}${indent}${indent}${indent}${indent}properties = {${newline}`
              
              Object.entries(keyframe.properties).forEach(([key, value]) => {
                const luaValue = convertToLuaValue(value, key)
                if (luaValue) {
                  code += `${indent}${indent}${indent}${indent}${indent}${indent}${key} = ${luaValue},${newline}`
                }
              })
              
              code += `${indent}${indent}${indent}${indent}${indent}},${newline}`
              
              // Add per-keyframe spring settings
              const keyframeSprSettings = keyframe.sprSettings || functionAnimation.sprSettings || sprSettings
              code += `${indent}${indent}${indent}${indent}${indent}sprSettings = {${newline}`
              code += `${indent}${indent}${indent}${indent}${indent}${indent}dampingRatio = ${keyframeSprSettings.dampingRatio},${newline}`
              code += `${indent}${indent}${indent}${indent}${indent}${indent}undampedFrequency = ${keyframeSprSettings.undampedFrequency}${newline}`
              code += `${indent}${indent}${indent}${indent}${indent}}${newline}`
              code += `${indent}${indent}${indent}${indent}},${newline}`
            })
            
            code += `${indent}${indent}${indent}}${newline}`
            code += `${indent}${indent}},${newline}`
          })
          
          code += `${indent}}${newline}`
          code += newline
          
          // Function animation variables
          code += `${indent}local functionAnimationTime = 0${newline}`
          code += `${indent}local functionIsPlaying = true${newline}`
          code += `${indent}local functionLastKeyframes = {}${newline}`
          code += `${indent}local functionDuration = ${functionAnimation.duration}${newline}`
          code += newline
          
          // Function animation update logic
          code += `${indent}local function updateFunctionAnimation()${newline}`
          code += `${indent}${indent}local deltaTime = RunService.Heartbeat:Wait()${newline}`
          code += `${indent}${indent}if not functionIsPlaying then return end${newline}`
          code += newline
          code += `${indent}${indent}functionAnimationTime = functionAnimationTime + deltaTime${newline}`
          code += newline
          code += `${indent}${indent}-- Handle animation end${newline}`
          code += `${indent}${indent}if functionAnimationTime >= functionDuration then${newline}`
          code += `${indent}${indent}${indent}functionIsPlaying = false${newline}`
          code += `${indent}${indent}${indent}return${newline}`
          code += `${indent}${indent}end${newline}`
          code += newline
          code += `${indent}${indent}for elementId, animData in pairs(functionAnimations) do${newline}`
          code += `${indent}${indent}${indent}local element = animData.element${newline}`
          code += `${indent}${indent}${indent}local keyframes = animData.keyframes${newline}`
          code += newline
          code += `${indent}${indent}${indent}-- Find current keyframe${newline}`
          code += `${indent}${indent}${indent}local currentKeyframe = nil${newline}`
          code += newline
          code += `${indent}${indent}${indent}for i, keyframe in ipairs(keyframes) do${newline}`
          code += `${indent}${indent}${indent}${indent}if keyframe.time <= functionAnimationTime then${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}currentKeyframe = keyframe${newline}`
          code += `${indent}${indent}${indent}${indent}end${newline}`
          code += `${indent}${indent}${indent}end${newline}`
          code += newline
          code += `${indent}${indent}${indent}if currentKeyframe then${newline}`
          code += `${indent}${indent}${indent}${indent}-- Only call SPR.target when entering a new keyframe${newline}`
          code += `${indent}${indent}${indent}${indent}local lastTime = functionLastKeyframes[elementId]${newline}`
          code += `${indent}${indent}${indent}${indent}if not lastTime or lastTime ~= currentKeyframe.time then${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}-- Use keyframe-specific spring settings${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}local keyframeSprSettings = currentKeyframe.sprSettings${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}SPR.target(element, keyframeSprSettings.dampingRatio, keyframeSprSettings.undampedFrequency, currentKeyframe.properties)${newline}`
          code += `${indent}${indent}${indent}${indent}${indent}functionLastKeyframes[elementId] = currentKeyframe.time${newline}`
          code += `${indent}${indent}${indent}${indent}end${newline}`
          code += `${indent}${indent}${indent}end${newline}`
          code += `${indent}${indent}end${newline}`
          code += `${indent}end${newline}`
          code += newline
          
          // Start the function animation with a coroutine
          code += `${indent}-- Start function animation${newline}`
          code += `${indent}coroutine.wrap(function()${newline}`
          code += `${indent}${indent}while functionIsPlaying do${newline}`
          code += `${indent}${indent}${indent}updateFunctionAnimation()${newline}`
          code += `${indent}${indent}end${newline}`
          code += `${indent}end)()${newline}`
          
          code += `end${newline}`
          code += newline
          code += `${varName}.${func.eventName}:Connect(${varName}_${func.eventName})${newline}`
          code += newline
        })
      })
    }

    // Footer
    code += newline
    code += comment('End of generated code')

    return code
  }

  // Convert JavaScript values to Lua values
  function convertToLuaValue(value: any, propertyName?: string): string | null {
    if (value === null || value === undefined) return null

    if (typeof value === 'string') {
      // Handle string properties based on property name
      if (propertyName) {
        // Text properties
        if (propertyName === 'Text') {
          return `"${value.replace(/"/g, '\\"')}"`
        }
        
        // Enum properties - convert to Roblox enum format
        if (propertyName === 'TextXAlignment') {
          return `Enum.TextXAlignment.${value}`
        }
        if (propertyName === 'TextYAlignment') {
          return `Enum.TextYAlignment.${value}`
        }
        if (propertyName === 'Font') {
          return `Enum.Font.${value}`
        }
        if (propertyName === 'ScaleType') {
          return `Enum.ScaleType.${value}`
        }
        if (propertyName === 'ScrollingDirection') {
          return `Enum.ScrollingDirection.${value}`
        }
        if (propertyName === 'ElasticBehavior') {
          return `Enum.ElasticBehavior.${value}`
        }
        if (propertyName === 'Image') {
          return `"${value}"`
        }
      }
      
      // For other string properties, quote them
      return `"${value.replace(/"/g, '\\"')}"`
    }

    if (typeof value === 'number') {
      return value.toString()
    }

    if (typeof value === 'boolean') {
      return value.toString()
    }

    // UDim2
    if (value.X && value.Y && typeof value.X.Scale === 'number') {
      return `UDim2.new(${value.X.Scale}, ${value.X.Offset}, ${value.Y.Scale}, ${value.Y.Offset})`
    }

    // Color3
    if (typeof value.R === 'number' && typeof value.G === 'number' && typeof value.B === 'number') {
      return `Color3.new(${value.R}, ${value.G}, ${value.B})`
    }

    // Vector2
    if (typeof value.X === 'number' && typeof value.Y === 'number') {
      return `Vector2.new(${value.X}, ${value.Y})`
    }

    return null
  }

  // Copy to clipboard
  const copyToClipboard = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(generatedCode)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
    }
  }

  // Download as file
  const downloadFile = (): void => {
    const filename = `${project.name.replace(/[^a-zA-Z0-9]/g, '_')}.${exportConfig.targetVersion === 'Luau' ? 'luau' : 'lua'}`
    const blob = new Blob([generatedCode], { type: 'text/plain;charset=utf-8' })
    saveAs(blob, filename)
  }

  // Download as .anim.json file (native format)
  const downloadAnimFile = (): void => {
    const animData = {
      version: '1.0',
      name: project.name,
      timestamp: new Date().toISOString(),
      elements: project.elements,
      animations: project.animations,
      canvasSettings: {
        width: 1024,
        height: 768,
        orientation: 'landscape'
      }
    }

    const filename = `${project.name.replace(/[^a-zA-Z0-9]/g, '_')}.anim.json`
    const blob = new Blob([JSON.stringify(animData, null, 2)], { type: 'application/json;charset=utf-8' })
    saveAs(blob, filename)
  }

  // Download as .zuix.json file
  const downloadZuixFile = (): void => {
    const zuixData: ZuixFile = {
      version: '1.0',
      name: project.name,
      timestamp: new Date().toISOString(),
      elements: project.elements.map(element => ({
        id: element.id,
        type: element.type.toLowerCase(),
        name: element.name,
        position: {
          x: (element.properties.Position?.X?.Scale || 0) * 1024 + (element.properties.Position?.X?.Offset || 0),
          y: (element.properties.Position?.Y?.Scale || 0) * 768 + (element.properties.Position?.Y?.Offset || 0)
        },
        size: {
          width: (element.properties.Size?.X?.Scale || 0) * 1024 + (element.properties.Size?.X?.Offset || 0),
          height: (element.properties.Size?.Y?.Scale || 0) * 768 + (element.properties.Size?.Y?.Offset || 0)
        },
        parent: 'script.Parent',
        properties: {
          backgroundColor: color3ToHex(element.properties.BackgroundColor3),
          textColor: color3ToHex(element.properties.TextColor3),
          fontSize: element.properties.TextSize || 16,
          text: element.properties.Text || '',
          cornerRadius: element.properties.UICorner?.CornerRadius?.Offset || 0,
          transparency: element.properties.BackgroundTransparency || 0,
          zIndex: element.properties.ZIndex || 0,
          borderColor: color3ToHex(element.properties.BorderColor3),
          borderSizePixel: element.properties.BorderSizePixel || 1,
          rotation: 0,
          visible: element.properties.Visible !== false,
          clipDescendants: element.properties.ClipsDescendants || false,
          textStrokeColor: '#000000',
          textStrokeTransparency: 1,
          textScaled: element.properties.TextScaled || false,
          textWrapped: false,
          textXAlignment: element.properties.TextXAlignment || 'Center',
          textYAlignment: element.properties.TextYAlignment || 'Center',
          image: element.properties.Image || '',
          imageColor: color3ToHex(element.properties.ImageColor3),
          imageTransparency: element.properties.ImageTransparency || 0,
          scaleType: element.properties.ScaleType || 'Stretch',
          anchorPoint: {
            x: element.properties.AnchorPoint?.X || 0,
            y: element.properties.AnchorPoint?.Y || 0
          },
          layoutOrder: 0,
          sizeConstraint: 'RelativeXY'
        }
      })),
      canvasResolution: {
        width: 1024,
        height: 768,
        name: 'Default',
        category: 'default'
      }
    }

    const filename = `${project.name.replace(/[^a-zA-Z0-9]/g, '_')}.zuix.json`
    const blob = new Blob([JSON.stringify(zuixData, null, 2)], { type: 'application/json;charset=utf-8' })
    saveAs(blob, filename)
  }

  // Helper function to convert Color3 to hex
  const color3ToHex = (color: any) => {
    if (!color) return '#ffffff'
    const r = Math.round((color.R || 0) * 255)
    const g = Math.round((color.G || 0) * 255)
    const b = Math.round((color.B || 0) * 255)
    return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`
  }

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="w-[95vw] max-w-6xl h-[90vh] max-h-[90vh] bg-gray-900 border-gray-700 overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="text-white flex items-center gap-2">
            <Download className="w-5 h-5" />
            Export Lua Code
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="code" className="w-full flex-1 flex flex-col overflow-hidden">
          <TabsList className="grid w-full grid-cols-2 bg-gray-800">
            <TabsTrigger value="code" className="data-[state=active]:bg-gradient-to-r data-[state=active]:from-[#fff0f5] data-[state=active]:to-[#ff669e] data-[state=active]:text-black">
              Generated Code
            </TabsTrigger>
            <TabsTrigger value="settings">
              Export Settings
            </TabsTrigger>
          </TabsList>

          <TabsContent value="code" className="space-y-4 flex-1 overflow-y-auto">
            {/* Code Preview */}
            <div className="bg-gray-800 rounded-lg border border-gray-700">
              <div className="p-3 border-b border-gray-700 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Code className="w-4 h-4 text-[#e2d4ff]" />
                  <span className="font-medium text-white">
                    {project.name}.{exportConfig.targetVersion === 'Luau' ? 'luau' : 'lua'}
                  </span>
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={copyToClipboard}
                    className="text-gray-300 hover:text-white gap-2"
                  >
                    {copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </Button>
                  <div className="relative">
                    <Button
                      onClick={() => setShowExportDropdown(!showExportDropdown)}
                      className="bg-gradient-to-r from-[#fff0f5] to-[#ffd1db] text-black hover:from-[#ff669e] hover:to-[#ff4080] gap-2"
                      size="sm"
                    >
                      <Download className="w-4 h-4" />
                      Export
                    </Button>
                    
                    <AnimatePresence>
                      {showExportDropdown && (
                        <motion.div
                          initial={{ opacity: 0, y: -10, scale: 0.95 }}
                          animate={{ opacity: 1, y: 0, scale: 1 }}
                          exit={{ opacity: 0, y: -10, scale: 0.95 }}
                          transition={{ duration: 0.2 }}
                          className="absolute top-full right-0 mt-2 bg-gray-800 border border-gray-700 rounded-lg shadow-xl z-50 overflow-hidden min-w-48"
                        >
                          <div className="p-2">
                            <div className="text-xs font-medium text-gray-300 mb-2 px-2">Export Options</div>
                            <div className="space-y-1">
                              <Button
                                onClick={() => {
                                  downloadFile()
                                  setShowExportDropdown(false)
                                }}
                                variant="ghost"
                                className="w-full justify-start gap-2 text-gray-300 hover:text-white hover:bg-gray-700 p-2 h-auto"
                              >
                                <Code className="w-4 h-4" />
                                <div className="text-left">
                                  <div className="text-sm">Lua Code</div>
                                  <div className="text-xs text-gray-400">Working SPR animation code</div>
                                </div>
                              </Button>
                              <Button
                                onClick={() => {
                                  downloadAnimFile()
                                  setShowExportDropdown(false)
                                }}
                                variant="ghost"
                                className="w-full justify-start gap-2 text-gray-300 hover:text-white hover:bg-gray-700 p-2 h-auto"
                              >
                                <FileText className="w-4 h-4" />
                                <div className="text-left">
                                  <div className="text-sm">.anim.json</div>
                                  <div className="text-xs text-gray-400">Zomex•UIX project file</div>
                                </div>
                              </Button>

                            </div>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              </div>
              <ScrollArea className="h-96">
                <pre className="p-4 text-sm text-gray-300 font-mono whitespace-pre-wrap">
                  {generatedCode}
                </pre>
              </ScrollArea>
            </div>

            {/* Code Stats */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="bg-gray-800 rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-[#e2d4ff]">
                  {generatedCode.split('\n').length}
                </div>
                <div className="text-sm text-gray-400">Lines of Code</div>
              </div>
              <div className="bg-gray-800 rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-[#e2d4ff]">
                  {project.elements.length}
                </div>
                <div className="text-sm text-gray-400">UI Elements</div>
              </div>
              <div className="bg-gray-800 rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-[#e2d4ff]">
                  {project.animations.length}
                </div>
                <div className="text-sm text-gray-400">Keyframes</div>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="settings" className="space-y-6 flex-1 overflow-y-auto">
            {/* General Settings */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-white flex items-center gap-2">
                <Settings className="w-5 h-5" />
                General Settings
              </h3>
              
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="target-version" className="text-gray-300">Target Version</Label>
                  <select
                    id="target-version"
                    value={exportConfig.targetVersion}
                    onChange={(e) => setExportConfig(prev => ({ ...prev, targetVersion: e.target.value as 'Luau' | 'Lua5.1' }))}
                    className="w-full p-2 bg-gray-800 border border-gray-600 rounded text-white"
                  >
                    <option value="Luau">Luau (Recommended)</option>
                    <option value="Lua5.1">Lua 5.1 (Legacy)</option>
                  </select>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="include-comments" className="text-gray-300">Include Comments</Label>
                    <Switch
                      id="include-comments"
                      checked={exportConfig.includeComments}
                      onCheckedChange={(checked) => setExportConfig(prev => ({ ...prev, includeComments: checked }))}
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <Label htmlFor="minify" className="text-gray-300">Minify Code</Label>
                    <Switch
                      id="minify"
                      checked={exportConfig.minify}
                      onCheckedChange={(checked) => setExportConfig(prev => ({ ...prev, minify: checked }))}
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* ScreenGui Settings */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-white flex items-center gap-2">
                <Settings className="w-5 h-5" />
                ScreenGui Settings
              </h3>
              
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="screengui-name" className="text-gray-300">Name</Label>
                  <Input
                    id="screengui-name"
                    type="text"
                    value={exportConfig.screenGuiSettings?.name || 'ScreenGui'}
                    onChange={(e) => setExportConfig(prev => ({
                      ...prev,
                      screenGuiSettings: {
                        ...prev.screenGuiSettings,
                        name: e.target.value || 'ScreenGui',
                        ignoreGuiInset: prev.screenGuiSettings?.ignoreGuiInset ?? false,
                        resetOnSpawn: prev.screenGuiSettings?.resetOnSpawn ?? false,
                        displayOrder: prev.screenGuiSettings?.displayOrder ?? 0,
                        zIndexBehavior: prev.screenGuiSettings?.zIndexBehavior ?? 'Sibling',
                        autoLocalize: prev.screenGuiSettings?.autoLocalize ?? false,
                        enabled: prev.screenGuiSettings?.enabled ?? true
                      }
                    }))}
                    className="bg-gray-800 border-gray-600 text-white"
                  />
                  <p className="text-xs text-gray-400">The name of the ScreenGui object</p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="display-order" className="text-gray-300">Display Order</Label>
                  <Input
                    id="display-order"
                    type="number"
                    value={exportConfig.screenGuiSettings?.displayOrder ?? 0}
                    onChange={(e) => setExportConfig(prev => ({
                      ...prev,
                      screenGuiSettings: {
                        ...prev.screenGuiSettings,
                        name: prev.screenGuiSettings?.name || 'ScreenGui',
                        ignoreGuiInset: prev.screenGuiSettings?.ignoreGuiInset ?? false,
                        resetOnSpawn: prev.screenGuiSettings?.resetOnSpawn ?? false,
                        displayOrder: parseInt(e.target.value) || 0,
                        zIndexBehavior: prev.screenGuiSettings?.zIndexBehavior ?? 'Sibling',
                        autoLocalize: prev.screenGuiSettings?.autoLocalize ?? false,
                        enabled: prev.screenGuiSettings?.enabled ?? true
                      }
                    }))}
                    className="bg-gray-800 border-gray-600 text-white"
                  />
                  <p className="text-xs text-gray-400">Controls the display order of this ScreenGui</p>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="zindex-behavior" className="text-gray-300">ZIndex Behavior</Label>
                  <select
                    id="zindex-behavior"
                    value={exportConfig.screenGuiSettings?.zIndexBehavior || 'Sibling'}
                    onChange={(e) => setExportConfig(prev => ({
                      ...prev,
                      screenGuiSettings: {
                        ...prev.screenGuiSettings,
                        name: prev.screenGuiSettings?.name || 'ScreenGui',
                        ignoreGuiInset: prev.screenGuiSettings?.ignoreGuiInset ?? false,
                        resetOnSpawn: prev.screenGuiSettings?.resetOnSpawn ?? false,
                        displayOrder: prev.screenGuiSettings?.displayOrder ?? 0,
                        zIndexBehavior: e.target.value as 'Sibling' | 'Global',
                        autoLocalize: prev.screenGuiSettings?.autoLocalize ?? false,
                        enabled: prev.screenGuiSettings?.enabled ?? true
                      }
                    }))}
                    className="w-full p-2 bg-gray-800 border border-gray-600 rounded text-white"
                  >
                    <option value="Sibling">Sibling</option>
                    <option value="Global">Global</option>
                  </select>
                  <p className="text-xs text-gray-400">How ZIndex values are calculated</p>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <Label htmlFor="ignore-gui-inset" className="text-gray-300">Ignore Gui Inset</Label>
                      <p className="text-xs text-gray-400 mt-1">Ignore top bar on mobile devices</p>
                    </div>
                    <Switch
                      id="ignore-gui-inset"
                      checked={exportConfig.screenGuiSettings?.ignoreGuiInset ?? false}
                      onCheckedChange={(checked) => setExportConfig(prev => ({
                        ...prev,
                        screenGuiSettings: {
                          ...prev.screenGuiSettings,
                          name: prev.screenGuiSettings?.name || 'ScreenGui',
                          ignoreGuiInset: checked,
                          resetOnSpawn: prev.screenGuiSettings?.resetOnSpawn ?? false,
                          displayOrder: prev.screenGuiSettings?.displayOrder ?? 0,
                          zIndexBehavior: prev.screenGuiSettings?.zIndexBehavior ?? 'Sibling',
                          autoLocalize: prev.screenGuiSettings?.autoLocalize ?? false,
                          enabled: prev.screenGuiSettings?.enabled ?? true
                        }
                      }))}
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label htmlFor="reset-on-spawn" className="text-gray-300">Reset On Spawn</Label>
                      <p className="text-xs text-gray-400 mt-1">Reset GUI when player respawns</p>
                    </div>
                    <Switch
                      id="reset-on-spawn"
                      checked={exportConfig.screenGuiSettings?.resetOnSpawn ?? false}
                      onCheckedChange={(checked) => setExportConfig(prev => ({
                        ...prev,
                        screenGuiSettings: {
                          ...prev.screenGuiSettings,
                          name: prev.screenGuiSettings?.name || 'ScreenGui',
                          ignoreGuiInset: prev.screenGuiSettings?.ignoreGuiInset ?? false,
                          resetOnSpawn: checked,
                          displayOrder: prev.screenGuiSettings?.displayOrder ?? 0,
                          zIndexBehavior: prev.screenGuiSettings?.zIndexBehavior ?? 'Sibling',
                          autoLocalize: prev.screenGuiSettings?.autoLocalize ?? false,
                          enabled: prev.screenGuiSettings?.enabled ?? true
                        }
                      }))}
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label htmlFor="auto-localize" className="text-gray-300">Auto Localize</Label>
                      <p className="text-xs text-gray-400 mt-1">Automatically translate text content</p>
                    </div>
                    <Switch
                      id="auto-localize"
                      checked={exportConfig.screenGuiSettings?.autoLocalize ?? false}
                      onCheckedChange={(checked) => setExportConfig(prev => ({
                        ...prev,
                        screenGuiSettings: {
                          ...prev.screenGuiSettings,
                          name: prev.screenGuiSettings?.name || 'ScreenGui',
                          ignoreGuiInset: prev.screenGuiSettings?.ignoreGuiInset ?? false,
                          resetOnSpawn: prev.screenGuiSettings?.resetOnSpawn ?? false,
                          displayOrder: prev.screenGuiSettings?.displayOrder ?? 0,
                          zIndexBehavior: prev.screenGuiSettings?.zIndexBehavior ?? 'Sibling',
                          autoLocalize: checked,
                          enabled: prev.screenGuiSettings?.enabled ?? true
                        }
                      }))}
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label htmlFor="enabled" className="text-gray-300">Enabled</Label>
                      <p className="text-xs text-gray-400 mt-1">Whether the GUI is active</p>
                    </div>
                    <Switch
                      id="enabled"
                      checked={exportConfig.screenGuiSettings?.enabled ?? true}
                      onCheckedChange={(checked) => setExportConfig(prev => ({
                        ...prev,
                        screenGuiSettings: {
                          ...prev.screenGuiSettings,
                          name: prev.screenGuiSettings?.name || 'ScreenGui',
                          ignoreGuiInset: prev.screenGuiSettings?.ignoreGuiInset ?? false,
                          resetOnSpawn: prev.screenGuiSettings?.resetOnSpawn ?? false,
                          displayOrder: prev.screenGuiSettings?.displayOrder ?? 0,
                          zIndexBehavior: prev.screenGuiSettings?.zIndexBehavior ?? 'Sibling',
                          autoLocalize: prev.screenGuiSettings?.autoLocalize ?? false,
                          enabled: checked
                        }
                      }))}
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* SPR Animation Settings */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-white flex items-center gap-2">
                <Zap className="w-5 h-5" />
                Animation Settings
              </h3>
              
              <div className="space-y-4">


                <div className="space-y-2">
                  <Label className="text-gray-300">Animation Type</Label>
                  <select
                    value={exportConfig.animationType || 'loop'}
                    onChange={(e) => setExportConfig(prev => ({ ...prev, animationType: e.target.value as 'loop' | 'playOnce' }))}
                    className="w-full p-2 bg-gray-800 border border-gray-600 rounded text-white"
                  >
                    <option value="loop">Loop Animation</option>
                    <option value="playOnce">Play Once</option>
                  </select>
                  <p className="text-xs text-gray-400">
                    Choose whether the animation loops continuously or plays once
                  </p>
                </div>


              </div>
            </div>

            {/* SPR Library Info */}
            <div className="bg-blue-900/20 border border-blue-600/30 rounded-lg p-4">
              <h4 className="font-medium text-blue-300 mb-2">SPR Library Required</h4>
              <p className="text-sm text-blue-200 mb-3">
                This code requires the SPR animation library by Fraktality. Make sure to include it in your project.
              </p>
              <Button
                variant="outline"
                size="sm"
                onClick={() => window.open('https://github.com/Fraktality/spr', '_blank')}
                className="border-blue-600 text-blue-300 hover:bg-blue-900/30"
              >
                <FileText className="w-4 h-4 mr-2" />
                View SPR Documentation
              </Button>
            </div>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  )
}